import { createContext, useState } from "react";

export const PopupContext = createContext();

export function PopupProvider({ children }) {
  const [allMovies, setAllMovies] = useState(initialMovies);
  const [detailClickingSeries, setDetailClickingSeries] = useState(false);
  const [detailClickingFilm, setDetailClickingFilm] = useState(false);
  const [versiPembayaran, setVersiPembayaran] = useState(null);
  const [isSubscribe, setIsSubscribe] = useState(false);

  return (
    <PopupContext.Provider
      value={{
        allMovies,
        setAllMovies,
        detailClickingSeries,
        setDetailClickingSeries,
        detailClickingFilm,
        setDetailClickingFilm,
        versiPembayaran,
        setVersiPembayaran,
        isSubscribe,
        setIsSubscribe,
      }}
    >
      {children}
    </PopupContext.Provider>
  );
}

const initialMovies = [
  {
    imageUrl: "Number=1.png",
    title: "Shadow of Vengeance",
    genre: ["Aksi", "Thriller", "Drama"],
    duration: 101,
    description:
      "A retired soldier seeks justice after his family is taken from him. He faces a dangerous underworld to uncover the truth.",
    cast: [
      "Ethan Cross",
      "Laura Miles",
      "Derek Vance",
      "Sophie Turner",
      "Mark Hayes",
      "Anna Cole",
    ],
    filmmaker: ["James Nolan", "Rebecca Moore", "David Stern"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "1",
  },
  {
    imageUrl: "Number=2.png",
    title: "Mystic Horizons",
    genre: ["Fantasi", "Petualangan", "Drama"],
    duration: 110,
    description:
      "A young girl discovers a portal to another world filled with magic. She must navigate dangerous alliances to save her village.",
    cast: [
      "Clara Finn",
      "Oliver Drake",
      "Liam Parker",
      "Sasha Reed",
      "Amelia Stone",
    ],
    filmmaker: ["Harvey Kent", "Melissa Ford", "Tina Andrews"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "13+",
    rating: 0,
    id: "2",
  },
  {
    imageUrl: "Number=3.png",
    title: "Urban Heat",
    genre: ["Kejahatan", "Aksi", "Thriller"],
    duration: 94,
    description:
      "An undercover cop is forced to blur the lines between right and wrong. His loyalty is tested in the crime-ridden streets of the city.",
    cast: [
      "Jason Ford",
      "Kelly Burns",
      "Victor Holt",
      "Lucy Hale",
      "Patrick Dean",
    ],
    filmmaker: ["Shawn Matthews", "Rachel King", "Edward Lane"],
    release: 2023,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "3",
  },
  {
    imageUrl: "Number=4.png",
    title: "Dawn Raiders",
    genre: ["Perang", "Petualangan", "Drama"],
    duration: 105,
    description:
      "A group of soldiers set out on a mission to turn the tide of a losing battle. Their courage and loyalty are pushed to the limit.",
    cast: [
      "Nathaniel Scott",
      "Emma Rose",
      "Carlos Vega",
      "David Monroe",
      "Isla Brooks",
    ],
    filmmaker: ["Samantha Blair", "Timothy Adams", "Frank Benson"],
    release: 2020,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "4",
  },
  {
    imageUrl: "Number=5.png",
    title: "Whispers of the Wild",
    genre: ["Sains dan Alam", "Petualangan", "Anak Anak"],
    duration: 88,
    description:
      "A brother and sister explore an untouched wilderness teeming with life. Their bond with nature leads them on an unforgettable journey.",
    cast: [
      "Ella Bright",
      "Liam Collins",
      "Sophie Mitchell",
      "James Foster",
      "Zoe Adams",
    ],
    filmmaker: ["George Turner", "Isabelle Clarke", "Ben Foster"],
    release: 2019,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "7+",
    rating: 0,
    id: "5",
  },
  {
    imageUrl: "Number=6.png",
    title: "Crimson Skies",
    genre: ["Aksi", "Petualangan"],
    duration: 103,
    description:
      "A rogue pilot must stop a warlord from unleashing chaos across nations. Along the way, he discovers his true heritage.",
    cast: ["Jake Nolan", "Maria Vale", "Chris Ryder", "Eva Holt", "Sam Briggs"],
    filmmaker: ["Jonathan Stone", "Emily Rowe", "Victor Sharp"],
    release: 2024,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "13+",
    rating: 0,
    id: "6",
  },
  {
    imageUrl: "Number=7.png",
    title: "Silent Witness",
    genre: ["Thriller", "Misteri"],
    duration: 98,
    description:
      "A mute woman becomes the only witness to a brutal crime. She must find another way to communicate what she saw.",
    cast: ["Florence Pugh", "Riz Ahmed", "Olivia Colman", "Anthony Hopkins"],
    filmmaker: ["David Fincher", "Denis Villeneuve", "Kathryn Bigelow"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "7",
  },
  {
    imageUrl: "Number=8.png",
    title: "The Forgotten Kingdom",
    genre: ["Fantasi", "Petualangan"],
    duration: 122,
    description:
      "A young prince must reclaim his stolen throne from an evil sorcerer. His journey reveals the true meaning of leadership.",
    cast: ["Dev Patel", "Freida Pinto", "Aishwarya Rai", "Irrfan Khan"],
    filmmaker: ["Ang Lee", "Guillermo del Toro", "Jon Favreau"],
    release: 2019,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "13+",
    rating: 0,
    id: "8",
  },
  {
    imageUrl: "Number=9.png",
    title: "Deep Sea Discovery",
    genre: ["Petualangan", "Fantasi ilmiah"],
    duration: 106,
    description:
      "Scientists explore the deepest part of the ocean. They encounter creatures thought to be extinct for millions of years.",
    cast: ["Jason Momoa", "Emily Blunt", "Javier Bardem", "Anya Taylor-Joy"],
    filmmaker: ["James Cameron", "Steven Spielberg", "Guillermo del Toro"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "13+",
    rating: 0,
    id: "9",
  },
  {
    imageUrl: "Number=10.png",
    title: "The Hidden Truth",
    genre: ["Misteri", "Drama"],
    duration: 111,
    description:
      "A journalist investigates a decades-old missing persons case. Her discoveries reveal shocking government secrets.",
    cast: ["Rachel McAdams", "Jake Gyllenhaal", "Viola Davis", "Mark Ruffalo"],
    filmmaker: ["David Fincher", "Steven Spielberg", "Kathryn Bigelow"],
    release: 2020,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "10",
  },
  {
    imageUrl: "Number=11.png",
    title: "Robot Revolution",
    genre: ["Fantasi ilmiah", "Aksi"],
    duration: 129,
    description:
      "Artificial intelligence becomes self-aware and turns against humanity. A small group of survivors fights back using old technology.",
    cast: ["Tom Hardy", "Charlize Theron", "Idris Elba", "Ana de Armas"],
    filmmaker: ["Christopher Nolan", "Denis Villeneuve", "James Cameron"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "11",
  },
  {
    imageUrl: "Number=12.png",
    title: "The Final Witness",
    genre: ["Thriller", "Kejahatan"],
    duration: 105,
    description:
      "The sole witness to a murder must testify against a powerful crime boss. Protection officers try to keep her alive until trial.",
    cast: ["Emily Blunt", "Jake Gyllenhaal", "Viola Davis", "Riz Ahmed"],
    filmmaker: ["David Fincher", "Christopher Nolan", "Denis Villeneuve"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "12",
  },
  {
    imageUrl: "Number=13.png",
    title: "Arctic Storm",
    genre: ["Petualangan", "Drama"],
    duration: 117,
    description:
      "Researchers are trapped in an Arctic station during a massive storm. Their survival depends on working together despite personal conflicts.",
    cast: ["Jennifer Lawrence", "Tom Hardy", "Idris Elba", "Florence Pugh"],
    filmmaker: [
      "Alejandro González Iñárritu",
      "Kathryn Bigelow",
      "Steve McQueen",
    ],
    release: 2020,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "13+",
    rating: 0,
    id: "13",
  },
  {
    imageUrl: "Number=14.png",
    title: "The Secret Garden",
    genre: ["Fantasi", "Drama"],
    duration: 94,
    description:
      "An orphan discovers a magical hidden garden. Its healing powers transform her and those around her.",
    cast: ["Emma Watson", "Colin Firth", "Julie Walters", "Maggie Smith"],
    filmmaker: ["Greta Gerwig", "Wes Anderson", "Kenneth Branagh"],
    release: 2020,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "7+",
    rating: 0,
    id: "14",
  },
  {
    imageUrl: "Number=15.png",
    title: "Cyber Attack",
    genre: ["Thriller", "Fantasi ilmiah"],
    duration: 98,
    description:
      "Hackers launch a devastating attack on global networks. A lone programmer must stop them before critical systems fail.",
    cast: [
      "John David Washington",
      "Letitia Wright",
      "Daniel Kaluuya",
      "Lakeith Stanfield",
    ],
    filmmaker: ["Denis Villeneuve", "Cary Fukunaga", "David Fincher"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: false,
    premium: true,
    age_rating: "17+",
    rating: 0,
    id: "15",
  },
  {
    imageUrl: "Number=16.png",
    title: "The Last Emperor",
    genre: ["Drama", "Sejarah"],
    duration: 134,
    description:
      "The rise and fall of China's final emperor. His story reflects the dramatic changes in 20th century China.",
    cast: ["Chow Yun-fat", "Zhang Ziyi", "Donnie Yen", "Michelle Yeoh"],
    filmmaker: ["Zhang Yimou", "Ang Lee", "Wong Kar-wai"],
    release: 2017,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "16",
  },
  {
    imageUrl: "Number=17.png",
    title: "Dark Conspiracy",
    genre: ["Thriller", "Misteri"],
    duration: 113,
    description:
      "A journalist uncovers a government conspiracy. Her investigation puts her life in grave danger.",
    cast: ["Charlize Theron", "Jake Gyllenhaal", "Viola Davis", "Riz Ahmed"],
    filmmaker: ["David Fincher", "Christopher Nolan", "Kathryn Bigelow"],
    release: 2020,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "17",
  },
  {
    imageUrl: "Number=18.png",
    title: "The Lost Treasure",
    genre: ["Petualangan", "Aksi"],
    duration: 107,
    description:
      "Treasure hunters race to find a legendary pirate's gold. Their competition turns deadly when they reach the treasure island.",
    cast: ["Dwayne Johnson", "Emily Blunt", "Jack Black", "Kevin Hart"],
    filmmaker: ["Steven Spielberg", "Jon Favreau", "James Gunn"],
    release: 2018,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "18",
  },
  {
    imageUrl: "Number=19.png",
    title: "Space Rescue",
    genre: ["Fantasi ilmiah", "Aksi"],
    duration: 118,
    description:
      "Astronauts attempt a daring rescue mission in deep space. Their skills are pushed to the limit by unexpected technical failures.",
    cast: [
      "Sandra Bullock",
      "George Clooney",
      "Anne Hathaway",
      "John Krasinski",
    ],
    filmmaker: ["Ridley Scott", "Christopher Nolan", "James Cameron"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: false,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "19",
  },
  {
    imageUrl: "Number=20.png",
    title: "The Perfect Crime",
    genre: ["Thriller", "Kejahatan"],
    duration: 104,
    description:
      "A criminal mastermind executes an elaborate heist. His plan is threatened by an unexpected witness.",
    cast: ["Ryan Gosling", "Emma Stone", "Joaquin Phoenix", "Margot Robbie"],
    filmmaker: ["David Fincher", "Christopher Nolan", "Quentin Tarantino"],
    release: 2020,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "20",
  },
  {
    imageUrl: "Number=21.png",
    title: "Ancient Secrets",
    genre: ["Petualangan", "Misteri"],
    duration: 122,
    description:
      "Archaeologists uncover an ancient tomb with mysterious powers. They must solve its puzzles before rival treasure hunters do.",
    cast: ["Chris Pratt", "Bryce Dallas Howard", "Tom Holland", "Zendaya"],
    filmmaker: ["Steven Spielberg", "James Cameron", "Jon Favreau"],
    release: 2019,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: false,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "21",
  },
  {
    imageUrl: "Number=22.png",
    title: "Undercover Agent",
    genre: ["Thriller", "Aksi"],
    duration: 116,
    description:
      "An FBI agent goes deep undercover in a drug cartel. His mission becomes complicated when he develops sympathy for the cartel leader.",
    cast: [
      "Leonardo DiCaprio",
      "Jennifer Lawrence",
      "Javier Bardem",
      "John David Washington",
    ],
    filmmaker: ["Martin Scorsese", "David Fincher", "Kathryn Bigelow"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: false,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "22",
  },
  {
    imageUrl: "Number=23.png",
    title: "Magical Journey",
    genre: ["Fantasi", "Anak anak"],
    duration: 89,
    description:
      "A child discovers a portal to a magical world in their closet. They must help magical creatures reclaim their stolen kingdom.",
    cast: ["Jacob Tremblay", "Millie Bobby Brown", "Jack Black", "Awkwafina"],
    filmmaker: ["Steven Spielberg", "Jon Favreau", "Greta Gerwig"],
    release: 2020,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: true,
    premium: false,
    age_rating: "7+",
    rating: 0,
    id: "23",
  },
  {
    imageUrl: "Number=24.png",
    title: "The Last Stand",
    genre: ["Aksi", "Perang"],
    duration: 128,
    description:
      "Soldiers defend a strategic position against overwhelming forces. Their sacrifice becomes legendary in military history.",
    cast: ["Tom Hanks", "Gary Oldman", "Cillian Murphy", "Tom Hardy"],
    filmmaker: ["Christopher Nolan", "Steven Spielberg", "Ridley Scott"],
    release: 2017,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "24",
  },
  {
    imageUrl: "Number=25.png",
    title: "Ocean Mystery",
    genre: ["Petualangan", "Misteri"],
    duration: 97,
    description:
      "Marine biologists discover an unknown species in the deep sea. Their excitement turns to fear when the creature displays unexpected intelligence.",
    cast: ["Jason Momoa", "Emily Blunt", "Javier Bardem", "Anya Taylor-Joy"],
    filmmaker: ["James Cameron", "Steven Spielberg", "Guillermo del Toro"],
    release: 2019,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "25",
  },
  {
    imageUrl: "Number=26.png",
    title: "The Detective",
    genre: ["Thriller", "Kejahatan"],
    duration: 111,
    description:
      "A retired detective returns to solve one last case. The investigation leads him to confront his own dark past.",
    cast: ["Denzel Washington", "Jodie Foster", "Rami Malek", "Viola Davis"],
    filmmaker: ["David Fincher", "Christopher Nolan", "Denis Villeneuve"],
    release: 2020,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "26",
  },
  {
    imageUrl: "Number=27.png",
    title: "Dragon Kingdom",
    genre: ["Fantasi", "Petualangan"],
    duration: 106,
    description:
      "A young warrior must tame a dragon to save her village. Her journey reveals a forgotten bond between humans and dragons.",
    cast: ["Zendaya", "Tom Holland", "Awkwafina", "Donnie Yen"],
    filmmaker: ["Jon Favreau", "Patty Jenkins", "Guillermo del Toro"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "27",
  },
  {
    imageUrl: "Number=28.png",
    title: "The Heist",
    genre: ["Kejahatan", "Thriller"],
    duration: 119,
    description:
      "A crew of thieves plans the perfect bank robbery. Their plan unravels when an undercover cop infiltrates their team.",
    cast: ["Robert De Niro", "Al Pacino", "Margot Robbie", "Adam Driver"],
    filmmaker: ["Martin Scorsese", "Quentin Tarantino", "David Fincher"],
    release: 2018,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: false,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "28",
  },
  {
    imageUrl: "Number=29.png",
    title: "Space Frontier",
    genre: ["Fantasi ilmiah", "Petualangan"],
    duration: 132,
    description:
      "Colonists struggle to establish the first Mars settlement. Their mission is jeopardized by unexpected environmental disasters.",
    cast: [
      "Matt Damon",
      "Jessica Chastain",
      "Chiwetel Ejiofor",
      "Kristen Wiig",
    ],
    filmmaker: ["Ridley Scott", "Christopher Nolan", "James Cameron"],
    release: 2022,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: false,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "29",
  },
  {
    imageUrl: "Number=30.png",
    title: "Love in Paris",
    genre: ["Romantis", "Drama"],
    duration: 102,
    description:
      "Two strangers meet by chance in the City of Love. Their whirlwind romance faces challenges when their pasts catch up with them.",
    cast: ["Emma Stone", "Ryan Gosling", "Marion Cotillard", "Omar Sy"],
    filmmaker: ["Woody Allen", "Richard Linklater", "Wes Anderson"],
    release: 2019,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: false,
    premium: false,
    age_rating: "13+",
    rating: 0,
    id: "30",
  },
  {
    imageUrl: "Number=31.png",
    title: "Samurai's Honor",
    genre: ["Aksi", "Drama", "Sejarah"],
    duration: 125,
    description:
      "A disgraced samurai seeks redemption in feudal Japan. His journey leads him to protect a village from ruthless warlords.",
    cast: [
      "Hiroyuki Sanada",
      "Ken Watanabe",
      "Rinko Kikuchi",
      "Tadanobu Asano",
    ],
    filmmaker: ["Akira Kurosawa", "Takashi Miike", "Park Chan-wook"],
    release: 2017,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "31",
  },
  {
    imageUrl: "Number=32.png",
    title: "Code Breaker",
    genre: ["Thriller", "Aksi"],
    duration: 108,
    description:
      "A hacker is recruited to stop a cyber attack on national infrastructure. She discovers the attack is just the beginning of a larger conspiracy.",
    cast: [
      "Ryan Gosling",
      "Ana de Armas",
      "John David Washington",
      "Letitia Wright",
    ],
    filmmaker: ["David Fincher", "Denis Villeneuve", "Cary Fukunaga"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: true,
    new_episode: false,
    premium: false,
    age_rating: "17+",
    rating: 0,
    id: "32",
  },
  {
    imageUrl: "Type=1.png",
    title: "Midnight Heist",
    genre: ["Thriller", "Crime"],
    duration: 112,
    description:
      "A crew of thieves plans an elaborate museum robbery under the cover of a solar eclipse.",
    cast: ["Ryan Gosling", "Ana de Armas", "Daniel Craig"],
    filmmaker: ["David Fincher", "Christopher Nolan"],
    release: 2022,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.7,
    id: "33",
  },
  {
    imageUrl: "Type=2.png",
    title: "Arctic Survival",
    genre: ["Adventure", "Drama"],
    duration: 98,
    description:
      "A research team must survive after their plane crashes in the Arctic wilderness.",
    cast: ["Jennifer Lawrence", "Tom Hardy", "Idris Elba"],
    filmmaker: ["Alejandro González Iñárritu"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.8,
    id: "34",
  },
  {
    imageUrl: "Type=3.png",
    title: "Neon Dreams",
    genre: ["Sci-Fi", "Mystery"],
    duration: 105,
    description:
      "A hacker discovers a virtual world where people's dreams are being stolen.",
    cast: ["John David Washington", "Letitia Wright", "Steven Yeun"],
    filmmaker: ["Denis Villeneuve"],
    release: 2023,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.6,
    id: "35",
  },
  {
    imageUrl: "Type=4.png",
    title: "The Last Duel",
    genre: ["Historical", "Drama"],
    duration: 132,
    description:
      "Two knights face off in France's last legally sanctioned duel.",
    cast: ["Matt Damon", "Adam Driver", "Jodie Comer"],
    filmmaker: ["Ridley Scott"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.9,
    id: "36",
  },
  {
    imageUrl: "Type=5.png",
    title: "Shadow Protocol",
    genre: ["Action", "Thriller"],
    duration: 107,
    description:
      "A black ops agent uncovers a conspiracy within his own organization.",
    cast: ["Chris Hemsworth", "Jessica Chastain", "Benedict Cumberbatch"],
    filmmaker: ["Kathryn Bigelow"],
    release: 2022,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.5,
    id: "37",
  },
  {
    imageUrl: "Type=6.png",
    title: "Island of the Lost",
    genre: ["Adventure", "Mystery"],
    duration: 115,
    description:
      "Explorers discover a mysterious island that shouldn't exist on any maps.",
    cast: ["Dwayne Johnson", "Emily Blunt", "Jack Black"],
    filmmaker: ["Steven Spielberg"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.7,
    id: "38",
  },
  {
    imageUrl: "Type=7.png",
    title: "Quantum Paradox",
    genre: ["Sci-Fi", "Thriller"],
    duration: 121,
    description:
      "A physicist accidentally creates a time loop and must find a way to break it.",
    cast: ["Robert Downey Jr.", "Elizabeth Olsen", "Benedict Wong"],
    filmmaker: ["Christopher Nolan"],
    release: 2023,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 4.8,
    id: "39",
  },
  {
    imageUrl: "Type=8.png",
    title: "The Silent Patient",
    genre: ["Thriller", "Mystery"],
    duration: 98,
    description:
      "A criminal psychologist tries to unravel why a famous artist shot her husband and then stopped speaking.",
    cast: ["Florence Pugh", "Riz Ahmed", "Olivia Colman"],
    filmmaker: ["David Fincher"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.9,
    id: "40",
  },
  {
    imageUrl: "Type=9.png",
    title: "Midnight Express",
    genre: ["Drama", "Crime"],
    duration: 104,
    description: "A young man's nightmare experience in a foreign prison.",
    cast: ["Timothée Chalamet", "Willem Dafoe", "Lakeith Stanfield"],
    filmmaker: ["Steve McQueen"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.6,
    id: "41",
  },
  {
    imageUrl: "Type=10.png",
    title: "The Forgotten Army",
    genre: ["War", "Drama"],
    duration: 127,
    description:
      "The untold story of Indian soldiers who fought in World War II.",
    cast: ["Dev Patel", "Freida Pinto", "Irrfan Khan"],
    filmmaker: ["Gurinder Chadha"],
    release: 2020,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.7,
    id: "42",
  },
  {
    imageUrl: "Type=11.png",
    title: "The Last Photograph",
    genre: ["Drama", "Mystery"],
    duration: 96,
    description:
      "A war photographer discovers a photo that holds the key to a decades-old mystery.",
    cast: ["Tom Hanks", "Viola Davis", "Riz Ahmed"],
    filmmaker: ["Steven Spielberg"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 4.5,
    id: "43",
  },
  {
    imageUrl: "Type=12.png",
    title: "Shadow and Bone",
    genre: ["Fantasy", "Adventure"],
    duration: 118,
    description:
      "A young soldier discovers she has magical powers that could unite her war-torn world.",
    cast: ["Jessie Mei Li", "Ben Barnes", "Amita Suman"],
    filmmaker: ["Eric Heisserer"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.8,
    id: "44",
  },
  {
    imageUrl: "Type=13.png",
    title: "The Irregulars",
    genre: ["Mystery", "Crime"],
    duration: 102,
    description:
      "A group of street teens work for Dr. Watson to solve supernatural crimes in Victorian London.",
    cast: ["McKell David", "Thaddea Graham", "Jojo Macari"],
    filmmaker: ["Tom Bidwell"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.6,
    id: "45",
  },
  {
    imageUrl: "Type=14.png",
    title: "Behind Her Eyes",
    genre: ["Thriller", "Drama"],
    duration: 108,
    description:
      "A single mother enters a world of twisted mind games when she begins an affair with her psychiatrist boss.",
    cast: ["Simona Brown", "Tom Bateman", "Eve Hewson"],
    filmmaker: ["Steve Lightfoot"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.7,
    id: "46",
  },
  {
    imageUrl: "Type=15.png",
    title: "The One",
    genre: ["Sci-Fi", "Thriller"],
    duration: 95,
    description:
      "A DNA researcher discovers a way to find everyone's perfect partner - with devastating consequences.",
    cast: ["Hannah Ware", "Dimitri Leonidas", "Amanda Drew"],
    filmmaker: ["Howard Overman"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.5,
    id: "47",
  },
  {
    imageUrl: "Type=16.png",
    title: "Sweet Tooth",
    genre: ["Fantasy", "Drama"],
    duration: 112,
    description:
      "A boy who's half-human, half-deer searches for a new beginning in a post-apocalyptic world.",
    cast: ["Christian Convery", "Nonso Anozie", "Adeel Akhtar"],
    filmmaker: ["Jim Mickle"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.8,
    id: "48",
  },
  {
    imageUrl: "Type=17.png",
    title: "Clickbait",
    genre: ["Thriller", "Mystery"],
    duration: 104,
    description:
      "When a family man is kidnapped, his loved ones discover disturbing secrets as they search for answers.",
    cast: ["Adrian Grenier", "Zoe Kazan", "Betty Gabriel"],
    filmmaker: ["Tony Ayres"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.6,
    id: "49",
  },
  {
    imageUrl: "Type=18.png",
    title: "The Witcher: Nightmare of the Wolf",
    genre: ["Animation", "Fantasy"],
    duration: 83,
    description:
      "A prequel to The Witcher series, exploring the origins of Geralt's mentor Vesemir.",
    cast: ["Theo James", "Lara Pulver", "Graham McTavish"],
    filmmaker: ["Kwang Il Han"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.9,
    id: "50",
  },
  {
    imageUrl: "Type=19.png",
    title: "Beyond the Horizon",
    genre: ["Adventure", "Sci-Fi"],
    duration: 110,
    description:
      "A team ventures beyond the known universe and encounters unexpected civilizations.",
    cast: ["Oscar Isaac", "Brie Larson", "Mahershala Ali"],
    filmmaker: ["James Cameron"],
    release: 2022,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 4.7,
    id: "51",
  },
  {
    imageUrl: "Type=20.png",
    title: "Crimson Tide",
    genre: ["Drama", "Thriller"],
    duration: 99,
    description:
      "A submarine crew faces internal conflict while trying to prevent global war.",
    cast: ["Denzel Washington", "Gene Hackman", "Scarlett Johansson"],
    filmmaker: ["Tony Scott"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.8,
    id: "52",
  },
  {
    imageUrl: "Type=21.png",
    title: "Forgotten Realms",
    genre: ["Fantasy", "Adventure"],
    duration: 120,
    description: "A hidden world of magic is discovered beneath a modern city.",
    cast: ["Millie Bobby Brown", "David Harbour", "Winona Ryder"],
    filmmaker: ["Guillermo del Toro"],
    release: 2023,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 4.9,
    id: "53",
  },
  {
    imageUrl: "Type=22.png",
    title: "Silent Echoes",
    genre: ["Mystery", "Thriller"],
    duration: 101,
    description:
      "A deaf detective solves crimes by reading subtle body language cues.",
    cast: ["Emily Blunt", "Cillian Murphy", "John Krasinski"],
    filmmaker: ["Jordan Peele"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.7,
    id: "54",
  },
  {
    imageUrl: "Type=23.png",
    title: "Echo Chamber",
    genre: ["Sci-Fi", "Drama"],
    duration: 113,
    description:
      "A social media platform spirals out of control, shaping reality itself.",
    cast: ["Anya Taylor-Joy", "Rami Malek", "J.K. Simmons"],
    filmmaker: ["Lana Wachowski"],
    release: 2023,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.8,
    id: "55",
  },
  {
    imageUrl: "Type=24.png",
    title: "Undercover",
    genre: ["Action", "Thriller"],
    duration: 102,
    description:
      "An agent goes deep into a criminal empire, risking everything.",
    cast: ["Charlize Theron", "Michael Fassbender", "Pedro Pascal"],
    filmmaker: ["Kathryn Bigelow"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "17+",
    rating: 4.9,
    id: "56",
  },
  {
    imageUrl: "Type=25.png",
    title: "Ghosts of Mars",
    genre: ["Sci-Fi", "Horror"],
    duration: 96,
    description:
      "Colonists on Mars face deadly hauntings after awakening ancient forces.",
    cast: ["Oscar Isaac", "Jessica Chastain", "Jason Momoa"],
    filmmaker: ["John Carpenter"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.6,
    id: "57",
  },
  {
    imageUrl: "Type=26.png",
    title: "River of Time",
    genre: ["Fantasy", "Romance"],
    duration: 108,
    description:
      "Two souls fall in love across different centuries through a mystical river.",
    cast: ["Timothée Chalamet", "Zendaya", "Florence Pugh"],
    filmmaker: ["Peter Jackson"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.8,
    id: "58",
  },
  {
    imageUrl: "Type=27.png",
    title: "Beyond Redemption",
    genre: ["Crime", "Drama"],
    duration: 111,
    description:
      "An ex-criminal must confront his past when his daughter is kidnapped.",
    cast: ["Jake Gyllenhaal", "Emily Blunt", "Idris Elba"],
    filmmaker: ["Martin Scorsese"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.7,
    id: "59",
  },
  {
    imageUrl: "Type=28.png",
    title: "Fractured Earth",
    genre: ["Drama", "Thriller"],
    duration: 103,
    description:
      "A massive earthquake reveals secrets buried deep under Los Angeles.",
    cast: ["Mark Wahlberg", "Natalie Portman", "Donnie Yen"],
    filmmaker: ["Roland Emmerich"],
    release: 2023,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.9,
    id: "60",
  },
  {
    imageUrl: "Type=29.png",
    title: "Code of Silence",
    genre: ["Mystery", "Thriller"],
    duration: 98,
    description:
      "An ex-police officer investigates his brother's disappearance in a corrupt town.",
    cast: ["Chris Evans", "Jessica Alba", "Keanu Reeves"],
    filmmaker: ["Denis Villeneuve"],
    release: 2022,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.7,
    id: "61",
  },
  {
    imageUrl: "Type=30.png",
    title: "The Lost Signal",
    genre: ["Sci-Fi", "Mystery"],
    duration: 100,
    description:
      "A mysterious radio transmission leads a group of friends to an abandoned facility.",
    cast: ["Finn Wolfhard", "Sophia Lillis", "David Harbour"],
    filmmaker: ["Matt Reeves"],
    release: 2021,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.8,
    id: "62",
  },
  {
    imageUrl: "Type=31.png",
    title: "Edge of Tomorrow",
    genre: ["Action", "Sci-Fi"],
    duration: 113,
    description:
      "A soldier stuck in a time loop fights to save humanity from an alien invasion.",
    cast: ["Tom Cruise", "Emily Blunt"],
    filmmaker: ["Doug Liman"],
    release: 2021,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "13+",
    rating: 4.6,
    id: "63",
  },
  {
    imageUrl: "Type=32.png",
    title: "Gravity Wells",
    genre: ["Sci-Fi", "Thriller"],
    duration: 117,
    description:
      "A rogue planet threatens the solar system, and a desperate mission is launched.",
    cast: ["Sandra Bullock", "George Clooney"],
    filmmaker: ["Alfonso Cuarón"],
    release: 2022,
    category1: "series-chill",
    category2: "film-trending",
    top_ten: true,
    new_episode: true,
    premium: true,
    age_rating: "13+",
    rating: 4.9,
    id: "64",
  },
  {
    imageUrl: "Type=33.png",
    title: "Lucid Dreams",
    genre: ["Mystery", "Fantasy"],
    duration: 106,
    description:
      "A therapist discovers a way to enter her patients' dreams to heal their trauma.",
    cast: ["Jessica Chastain", "Joseph Gordon-Levitt", "Emma Stone"],
    filmmaker: ["Christopher Nolan"],
    release: 2023,
    category1: "top-rating",
    category2: "new-release",
    top_ten: false,
    new_episode: true,
    premium: false,
    age_rating: "17+",
    rating: 4.7,
    id: "65",
  },
];
